### ISSUE TITLE
build tests issue

### ISSUE THREAD

**Issue by archetipo** [gregkh/kdbus#30] opened 2014-12-22 14:01 UTC
CC [M]  /home/archetipo/devel/kdbus/queue.o
      CC [M]  /home/archetipo/devel/kdbus/util.o
      LD [M]  /home/archetipo/devel/kdbus/kdbus.o
        Building modules, stage 2.
        MODPOST 1 modules
        CC      /home/archetipo/devel/kdbus/kdbus.mod.o
        LD [M]  /home/archetipo/devel/kdbus/kdbus.ko
      make[1]: Leaving directory `/usr/src/linux-headers-3.17.1-031701-generic'
      make -C tools KERNELDIR=/usr/src/linux-headers-3.17.1-031701-generic                       KBUILD_MODNAME=kdbus
      make[1]: Entering directory `/home/archetipo/devel/kdbus/tools'
      make[1]: Nothing to be done for `all'.
      make[1]: Leaving directory `/home/archetipo/devel/kdbus/tools'
      make -C test KERNELDIR=/usr/src/linux-headers-3.17.1-031701-generic             KBUILD_MODNAME=kdbus
      make[1]: Entering directory `/home/archetipo/devel/kdbus/test'
        TARGET_CC kdbus-enum.o
        TARGET_CC kdbus-util.o
        TARGET_CC kdbus-test.o
        TARGET_CC test-activator.o
        TARGET_CC test-attach-flags.o
        TARGET_CC test-benchmark.o
        TARGET_CC test-bus.o
        TARGET_CC test-chat.o
        TARGET_CC test-connection.o
        TARGET_CC test-daemon.o
        TARGET_CC test-endpoint.o
        TARGET_CC test-fd.o
        TARGET_CC test-free.o
        TARGET_CC test-match.o
        TARGET_CC test-message.o
        TARGET_CC test-metadata-ns.o
        TARGET_CC test-monitor.o
        TARGET_CC test-names.o
        TARGET_CC test-policy.o
        TARGET_CC test-policy-ns.o
        TARGET_CC test-policy-priv.o
        TARGET_CC test-race.o
        TARGET_CC test-sync.o
        TARGET_CC test-timeout.o
        TARGET_LD kdbus-test
      kdbus-util.o: In function `do_cap_get_flag':
      /home/archetipo/devel/kdbus/test/kdbus-util.c:1495: undefined reference to `cap_get_flag'
      kdbus-util.o: In function `test_is_capable':
      /home/archetipo/devel/kdbus/test/kdbus-util.c:1520: undefined reference to `cap_get_proc'
      /home/archetipo/devel/kdbus/test/kdbus-util.c:1540: undefined reference to `cap_free'
      collect2: error: ld returned 1 exit status
      make[1]: *** [kdbus-test] Error 1
      make[1]: Leaving directory `/home/archetipo/devel/kdbus/test'
      make: *** [test] Error 2

kdbus : @7f121b18a359dd453409dd94708680cf6720fb81

**Comment by zonque** [comment] 2015-03-25 15:31
We had a number of hard dependencies of kdbus to various kernel versions in the past, which were unavoidable due to changes in the internal kernel APIs. Please try the upstream version that is in linux-next since some weeks. If your issue is still reproducible, please speak up.

**Comment by archetipo** [comment] 2015-04-02 15:32
thanks, i will try to test your suggestion , and i will report  result

**Comment by gregkh** [comment] 2015-04-04 19:11
Closing out for now, if still a problem, please let us know on the systemd mailing list.

**Closed by gregkh** 2015-04-04 19:11 UTC
